[package]
name = "edgedb-cli"
license = "MIT/Apache-2.0"
version = "1.0.0-alpha.4"
authors = ["MagicStack Inc. <hello@magic.io>"]
edition = "2018"

[dependencies]
edgeql-parser = {git = "https://github.com/edgedb/edgedb"}
edgedb-protocol = {git = "https://github.com/edgedb/edgedb-rust", features=["all-types"]}
edgedb-derive = {git = "https://github.com/edgedb/edgedb-rust"}
snafu = {version="0.6.0", features=["backtraces"]}
anyhow = "1.0.23"
async-std = {version="1.6.*", features=[
    # we need stdin/stdout and channel
    "unstable",
]}
bytes = "0.5.3"
rustyline = { git="https://github.com/tailhook/rustyline", branch="edgedb_20200710"}
clap = { git="https://github.com/clap-rs/clap", branch="master" }
strsim = "0.10.0"
whoami = "0.6.0"
atty = "0.2.13"
scram = "0.5.0"
rpassword = "4.0.3"
colorful = "0.2.1"
term_size = "0.3.1"
bigdecimal = "0.1.0"
num-bigint = "0.2.3"
humantime = "2.0.0"
once_cell = "1.3.1"
chrono = "0.4.0"
unicode-segmentation = "1.6.0"
typemap = "0.3.3"
serde = "1.0"
serde_json = "1.0"
dirs = "2.0.2"
uuid = "0.8.1"
prettytable-rs = {version="0.8.0", default-features=false}
tempfile = "3.1.0"
codespan = "0.9.2"
codespan-reporting = "0.9.2"
termcolor = "1.1.0"
async-listen = "0.2.0"
sha1 = "0.6.0"
textwrap = "0.11.0"
log = "0.4.8"
env_logger = "0.7.1"
os-release = "0.1.0"
surf = {version="2.0.0-alpha.2", features=["h1-client"], default-features=false}
native-tls = {version="0.2.4"}
thiserror = "1.0.16"
which = {version="3.1.1", default-features=false}
linked-hash-map = "0.5.3"
term = "0.5"
libc = "0.2.68"
async-ctrlc = {version="1.2.0", features=["stream"]}
urlencoding = "1.1.1"

[dev-dependencies]
assert_cmd = {git="https://github.com/tailhook/assert_cmd", branch="edgedb_20190513"}
predicates = "1.0.4"
pretty_assertions = "0.6.1"
shutdown_hooks = "0.1.0"
tar = "0.4.26"
test-case = "1.0.0"
openssl = "0.10.29"
tokio = {version="0.2.21", features=["rt-threaded"]}
warp = {version="0.2.3", default-features=false, features=["tls"]}

[features]
dev_mode = []
github_action_install = []

[target.'cfg(unix)'.dependencies]
signal = "0.7.0"

[target.'cfg(windows)'.dependencies]
winapi = "0.3.8"
winreg = "0.7.0"

[target.'cfg(unix)'.dev-dependencies]
rexpect = {git="https://github.com/tailhook/rexpect", branch="default_terminal_size"}

[target.'cfg(target_env="musl")'.dependencies]
native-tls = {version="0.2.4", features=["vendored"]}

[[bin]]
name = "edgedb"
path = "src/main.rs"

[profile.release]
debug = true
lto = true
