[package]
name = "edgedb-cli"
license = "MIT/Apache-2.0"
version = "1.0.0-rc.1"
authors = ["EdgeDB Inc. <hello@edgedb.com>"]
edition = "2018"

[dependencies]
edgeql-parser = {git = "https://github.com/edgedb/edgedb"}
edgedb-protocol = {git = "https://github.com/edgedb/edgedb-rust", features=["all-types"], branch="pings"}
edgedb-derive = {git = "https://github.com/edgedb/edgedb-rust", branch="pings"}
edgedb-client = {git = "https://github.com/edgedb/edgedb-rust", features=["admin_socket", "unstable"], branch="pings"}
snafu = {version="0.6.0", features=["backtraces"]}
anyhow = "1.0.23"
async-std = {version="1.9", features=[
    # need FutureExt::race
    "unstable"
]}
bytes = "1.0.1"
blake2b_simd = "0.5.11"
rustyline = { git="https://github.com/tailhook/rustyline", branch="edgedb_20210403"}
#clap = "3.0.0-beta.2"
clap = { git="https://github.com/clap-rs/clap" }
clap_generate = { git="https://github.com/clap-rs/clap" }
strsim = "0.10.0"
whoami = "1.1"
atty = "0.2.13"
scram = "0.5.0"
rpassword = "5"
colorful = "0.2.1"
term_size = "0.3.1"
bigdecimal = "0.2"
num-bigint = "0.3"
humantime = "2.0.0"
humantime-serde = "1.0.0"
once_cell = "1.3.1"
chrono = "0.4.0"
unicode-segmentation = "1.6.0"
anymap = "0.12.1"
serde = "1.0"
serde_json = "1.0"
serde_path_to_error = "0.1.3"
serde_str = {git="https://github.com/tailhook/serde-str"}
dirs = "3"
uuid = "0.8.1"
prettytable-rs = {version="0.8.0", default-features=false}
tempfile = "3.1.0"
codespan-reporting = "0.11"
termcolor = "1.1.0"
crossterm = "0.19.0"
async-listen = "0.2.0"
sha1 = "0.6.0"
hex = "0.4.3"
textwrap = {version="0.14.2", features=["terminal_size"]}
log = "0.4.8"
env_logger = "0.8.2"
os-release = "0.1.0"
surf = {version="2.2.0", features=["h1-client"], default-features=false}
native-tls = {version="0.2.4"}
thiserror = "1.0.16"
which = {version="4", default-features=false}
linked-hash-map = {version="0.5.3", features=["serde_impl"]}
term = "0.7"
libc = "0.2.68"
urlencoding = "1.1.1"
fn-error-context = "0.1.1"
combine = "4.2.1"
sha2 = "0.9.1"
base32 = "0.4.0"
rand = "0.8.2"
downcast-rs = "1.2.0"
base64 = "0.13"
ring = "0.16.15"
shell-words = "1.0.0"
wait-timeout = "0.2.0"
indicatif = "0.15.0"
url = "2.1.1"
immutable-chunkmap = "0.5.9"
regex = "1.4.5"
toml = "0.5.8"
termimad = "0.10.2"
minimad = "0.7.0"
edgedb-cli-derive = { path="edgedb-cli-derive" }
fs-err = "2.6.0"
pem = "0.8"
rustls = {version="0.19.1", features=["dangerous_configuration"]}
webpki = "0.21.4"
futures = "0.3.15"
futures-util = "0.3.15"
clicolors-control = "1.0.1"
backtrace = "0.3.61"
arc-swap = "1.4.0"
ctrlc = "3.2.0"
async-process = "1.2.0"
crossbeam-utils = "0.8.5"

[dev-dependencies]
assert_cmd = "2.0.2"
predicates = "1.0.4"
pretty_assertions = "0.6.1"
shutdown_hooks = "0.1.0"
tar = "0.4.26"
test-case = "1.1.0"
openssl = "0.10.30"
tokio = {version="1.1.0", features=["rt-multi-thread"]}
warp = {git="https://github.com/fantix/warp", rev = "dab7759", default-features=false, features=["tls"]}

[features]
dev_mode = []
github_action_install = []
github_nightly = []

[target.'cfg(unix)'.dependencies]
signal = "0.7.0"
signal-hook = {version="0.3.10", features=["iterator"]}

[target.'cfg(windows)'.dependencies]
winapi = "0.3.8"
winreg = "0.8.0"

[target.'cfg(unix)'.dev-dependencies]
rexpect = {git="https://github.com/tailhook/rexpect", branch="default_terminal_size"}
nix = "0.22.0"

[target.'cfg(target_env="musl")'.dependencies]
native-tls = {version="0.2.4", features=["vendored"]}

[[bin]]
name = "edgedb"
path = "src/main.rs"

[profile.release]
debug = true
lto = true

[patch.crates-io]
rustls = { git = "https://github.com/edgedb/rustls", rev = "480345e" }
